version: '3'

services:
  frontend:
    build: ./frontend-service
    ports:
      - "5000:5000"
    depends_on:
      - gateway

  gateway:
    build: ./gateway-service
    ports:
      - "5001:5000"
    depends_on:
      - student
      - professor
      - course

  student:
    build: ./account-student-service
    ports:
      - "5002:5000"

  professor:
    build: ./account-professor-service
    ports:
      - "5003:5000"

  course:
    build: ./course-service
    ports:
      - "5004:5000"
