# student-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student
  template:
    metadata:
      labels:
        app: student
    spec:
      containers:
      - name: student
        image: peripapapy/school-app-student
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: student
spec:
  selector:
    app: student
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
